version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Lisbon"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
